# Generated by Django 5.0.1 on 2024-01-29 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietChart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_image', models.ImageField(default='', upload_to='photos')),
                ('d_name', models.CharField(max_length=15)),
                ('d_description', models.TextField()),
                ('d_created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=30)),
                ('e_description', models.TextField()),
                ('e_image', models.FileField(default='', upload_to='photos')),
                ('calories_burned_per_minute', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('join_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=30, verbose_name='Meal_Name')),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fat', models.FloatField()),
                ('diet_chart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.dietchart_table')),
            ],
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('placed', 'placed'), ('pending', 'pending'), ('complete', 'complete')], default='', max_length=20)),
                ('amount', models.FloatField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.subscriptionplan_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='dietchart_table',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.subscriptionplan_table'),
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=10)),
                ('status1', models.CharField(choices=[('placed', 'placed'), ('pending', 'pending'), ('complete', 'complete')], default='', max_length=20)),
                ('time', models.DateTimeField()),
                ('a_amount', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.order_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=30)),
                ('i_gender', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.BigIntegerField()),
                ('message', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='dietchart_table',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='new.user_table'),
        ),
        migrations.CreateModel(
            name='CustomMeal_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=25)),
                ('meal_calories', models.FloatField()),
                ('meal_protein', models.FloatField()),
                ('meal_carbohydrates', models.FloatField()),
                ('meal_fat', models.FloatField()),
                ('meal_description', models.TextField()),
                ('meal_created_date', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('body_shape', models.CharField(max_length=25)),
                ('dieseas', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDietPlan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=30)),
                ('cp_description', models.TextField()),
                ('cp_created_date', models.DateField(auto_now=True)),
                ('diet_chart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.dietchart_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=40)),
                ('c_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=20)),
                ('complaint_datetime', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Card_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=30)),
                ('card_number', models.CharField(default='', max_length=16)),
                ('cvv', models.IntegerField()),
                ('card_expiry_date', models.DateField()),
                ('card_balance', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Workoutplan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=30)),
                ('w_description', models.TextField()),
                ('created_date', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
    ]
