# Generated by Django 5.0.1 on 2024-01-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='join_date',
        ),
    ]
