# Generated by Django 5.0.1 on 2024-01-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_remove_user_table_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietchart_table',
            name='user_id',
        ),
        migrations.AddField(
            model_name='dietchart_table',
            name='age',
            field=models.CharField(choices=[('10-20', '10-20'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60-70', '60-70'), ('70-80', '70-80')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dietchart_table',
            name='diseases',
            field=models.CharField(choices=[('Chickenpox', 'Chickenpox'), ('cholera', 'cholera'), ('malaria', 'malaria'), ('Dengue', 'Dengue'), ('Flu', 'Flu'), ('Plague', 'Plague'), ('corona', 'corona'), ('Infectious mononucleosis', 'Infectious mononucleosis.'), ('Liver Cancer', 'Liver Cancer')], default='', max_length=30),
        ),
    ]
