# Generated by Django 5.0.1 on 2024-01-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_remove_dietchart_table_user_id_dietchart_table_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_detail',
            name='body_shape',
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='age',
            field=models.CharField(choices=[('10-20', '10-20'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60-70', '60-70'), ('70-80', '70-80')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='dieseas',
            field=models.CharField(choices=[('Chickenpox', 'Chickenpox'), ('cholera', 'cholera'), ('malaria', 'malaria'), ('Dengue', 'Dengue'), ('Flu', 'Flu'), ('Plague', 'Plague'), ('corona', 'corona'), ('Infectious mononucleosis', 'Infectious mononucleosis.'), ('Liver Cancer', 'Liver Cancer')], max_length=30),
        ),
    ]
