# Generated by Django 5.0.1 on 2024-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_remove_customer_detail_body_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietchart_table',
            name='d_type',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Breakfast', 'Breakfast')], default='Lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='age',
            field=models.CharField(choices=[('10-25', '10-25'), ('25-40', '25-40'), ('40-55', '40-55'), ('55-70', '55-70')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='dieseas',
            field=models.CharField(choices=[('obesity', 'obesity'), ('cholesterol', 'cholesterol'), ('Heart health', 'Heart health'), ('Acidity', 'Acidity'), ('Blood Pressure', 'Blood Pressure'), ('Diabetes', 'Diabetes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dietchart_table',
            name='age',
            field=models.CharField(choices=[('10-25', '10-25'), ('25-40', '25-40'), ('40-55', '40-55'), ('55-70', '55-70')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dietchart_table',
            name='diseases',
            field=models.CharField(choices=[('obesity', 'obesity'), ('cholesterol', 'cholesterol'), ('Heart health', 'Heart health'), ('Acidity', 'Acidity'), ('Blood Pressure', 'Blood Pressure'), ('Diabetes', 'Diabetes')], default='', max_length=30),
        ),
    ]
