# Generated by Django 6.0.3 on 2026-04-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_alter_userprofile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=25)),
                ('amount', models.CharField(max_length=5)),
                ('message', models.TextField()),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_users',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='age_group',
            field=models.CharField(choices=[('10-25', '10-25'), ('25-40', '25-40'), ('40-55', '40-55'), ('55-70', '55-70')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='diseases',
            field=models.CharField(choices=[('obesity', 'obesity'), ('cholesterol', 'cholesterol'), ('Heart health', 'Heart health'), ('Acidity', 'Acidity'), ('Blood Pressure', 'Blood Pressure'), ('Diabetes', 'Diabetes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='image',
            field=models.ImageField(blank=True, upload_to='diet_charts/'),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment_needed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='target_muscle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='diseases',
            field=models.CharField(blank=True, choices=[('obesity', 'obesity'), ('cholesterol', 'cholesterol'), ('Heart health', 'Heart health'), ('Acidity', 'Acidity'), ('Blood Pressure', 'Blood Pressure'), ('Diabetes', 'Diabetes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
