# Generated by Django 6.0.3 on 2026-04-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_book_remove_workoutplan_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for exercise tutorial (e.g., https://www.youtube.com/watch?v=xxxxx)', null=True),
        ),
    ]
